const TEXT = {
  ko: {
    placeholder: "메시지를 입력하세요...",
    start: "시작하기",
    send: "전송",
    title: "MBTI 연애 테스트",
    back: "뒤로",
    phone: "음성 통화",
    video: "영상 통화",
    camera: "카메라",
    mic: "마이크",
    image: "사진",
    emoji: "이모지",
    messageInput: "메시지 입력",
    fetchFail: "응답을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.",
    networkFail: "응답을 불러오지 못했어요. 네트워크나 인증 상태를 확인해 주세요.",
    charactersTitle: "캐릭터 선택",
    tabChat: "채팅",
    tabCompatibility: "궁합",
    chatGuide:
      "나만의 캐릭터를 만들어 시작하거나, 아래 MBTI 책갈피에서 기본 프로필을 골라 대화해 보세요.",
    compatibilityGuide: "내 MBTI와 상대 MBTI를 입력해 궁합 결과를 확인해 보세요.",
    defaultMbtiCharacters: "기본 MBTI 캐릭터",
    loading: "불러오는 중…",
    customCharacterCreate: "나만의 캐릭터 만들기",
    customCharacterDesc:
      "사진과 프로필을 정한 뒤 대화를 시작해 보세요. 이미지는 이 브라우저에서만 미리보기용으로 쓰이며 서버로 전송되지 않아요.",
    preview: "미리보기",
    selectPhoto: "사진 선택",
    imageFormats: "JPG, PNG 등",
    name: "이름",
    characterName: "캐릭터 이름",
    mbti: "MBTI",
    identityNone: "선택 안 함",
    identityA: "A 자기확신형",
    identityT: "T 민감형",
    heightCm: "키 (cm)",
    weightKg: "몸무게 (kg)",
    gender: "성별",
    female: "여성",
    male: "남성",
    customDescriptionLabel: "커스텀 인물 설명",
    customDescriptionPlaceholder:
      "이 인물의 성격, 말투, 관계 설정, 좋아하는 것, 싫어하는 것 등을 자유롭게 적어주세요.",
    chatStyleSelect: "채팅 스타일 선택",
    instagramDm: "인스타 DM",
    kakao: "카톡",
    tiktokDm: "틱톡 DM",
    startWithCustom: "커스텀 캐릭터로 시작하기",
    atOptionOptional: "A/T 옵션 (선택 사항)",
    chatWithCharacter: "이 캐릭터와 채팅하기",
    myInfo: "내 정보",
    myName: "내 이름",
    partnerInfo: "상대 정보",
    partnerName: "상대 이름",
    viewCompatibility: "궁합 보기",
    viewResult: "궁합 보기",
    compatibilityScore: "궁합 점수",
    resultScore: "궁합 점수",
    compatibilityTitle: "궁합 결과",
    me: "나",
    partner: "상대",
    trust: "신뢰도",
    communication: "소통력",
    responsibilityBalance: "책임감 밸런스",
    humorChemistry: "유머 케미",
    landingHeroSubtitle: "지금, 너랑 가장 잘 맞는 사람은?",
    landingPreviewTitle: "이런 타입과 대화해요",
    landingPreviewDesc: "카드를 눌러 캐릭터를 골라 보세요",
    landingPreviewSeojunName: "서준",
    landingPreviewHaerinName: "해린",
    landingPreviewDoyunName: "도윤",
    landingPreviewSeojunLine: "같이 성장하는 연애, 멀리 갈 수 있지 않을까?",
    landingPreviewHaerinLine: "오늘 뭐 했어? 나한테도 다 말해줘, 진짜 궁금해!",
    landingPreviewDoyunLine: "말보다 행동으로 보여줄게. 같이 뭐 하나 만들어볼래?",
    landingChatTitle: "대화는 이렇게 이어져요",
    landingChatDesc: "인스타 DM처럼 익숙한 화면",
    landingChatMsg1: "안녕! 오늘 기분은 어때? 나한테도 말해줘.",
    landingChatMsg2: "솔직히... 요즘 좀 외로웠어.",
    landingChatMsg3: "그 마음, 충분히 이해해. 내가 옆에 있을게.",
    landingFeatureTitle: "왜 MBTI 연애 시뮬인가요",
    landingFeature1Title: "MBTI 기반 대화",
    landingFeature1Body:
      "16가지 타입별로 다른 말투와 반응. 진짜 그 사람과 대화하는 듯한 몰입을 느껴보세요.",
    landingFeature2Title: "감정 반응",
    landingFeature2Body:
      "공감, 설렘, 긴장까지. 메시지 하나하나에 캐릭터가 감정으로 답해요.",
    landingFeature3Title: "연애 시뮬레이션",
    landingFeature3Body:
      "부담 없이 대화만으로 연애 리허설. 오늘의 감정을 가볍게 풀어보세요.",
    landingEmotionalLine1: "밤에 혼자 떠올렸던 그 사람,",
    landingEmotionalLine2: "여기서 한 번 더 만나볼 수 있어요.",
    landingEmotionalSub: "부담 없이, 지금 이 순간만큼은 대화에만 집중해 보세요.",
  },
  en: {
    placeholder: "Type a message...",
    start: "Start",
    send: "Send",
    title: "MBTI Love Test",
    back: "Back",
    phone: "Voice call",
    video: "Video call",
    camera: "Camera",
    mic: "Microphone",
    image: "Photo",
    emoji: "Emoji",
    messageInput: "Message input",
    fetchFail: "Couldn't load a reply. Please try again in a moment.",
    networkFail:
      "Couldn't load a reply. Check your network or authentication status.",
    charactersTitle: "Character Selection",
    tabChat: "Chat",
    tabCompatibility: "Compatibility",
    chatGuide:
      "Create your own character or choose a default profile from the MBTI tabs below and start chatting.",
    compatibilityGuide:
      "Enter your MBTI and your partner's MBTI to check compatibility results.",
    defaultMbtiCharacters: "Default MBTI Characters",
    loading: "Loading...",
    customCharacterCreate: "Create Your Character",
    customCharacterDesc:
      "Set a photo and profile, then start chatting. The image is used only for local preview in this browser and is not uploaded.",
    preview: "Preview",
    selectPhoto: "Select Photo",
    imageFormats: "JPG, PNG, etc.",
    name: "Name",
    characterName: "Character name",
    mbti: "MBTI",
    identityNone: "No selection",
    identityA: "A Assertive",
    identityT: "T Turbulent",
    heightCm: "Height (cm)",
    weightKg: "Weight (kg)",
    gender: "Gender",
    female: "Female",
    male: "Male",
    customDescriptionLabel: "Custom Character Description",
    customDescriptionPlaceholder:
      "Describe this character's personality, speaking style, relationship setup, likes, and dislikes freely.",
    chatStyleSelect: "Chat Style",
    instagramDm: "Instagram DM",
    kakao: "KakaoTalk",
    tiktokDm: "TikTok DM",
    startWithCustom: "Start with Custom Character",
    atOptionOptional: "A/T option (optional)",
    chatWithCharacter: "Chat with this character",
    myInfo: "My Info",
    myName: "My name",
    partnerInfo: "Partner Info",
    partnerName: "Partner name",
    viewCompatibility: "View Compatibility",
    viewResult: "View Compatibility",
    compatibilityScore: "Compatibility Score",
    resultScore: "Compatibility Score",
    compatibilityTitle: "Compatibility Result",
    me: "Me",
    partner: "Partner",
    trust: "Trust",
    communication: "Communication",
    responsibilityBalance: "Responsibility Balance",
    humorChemistry: "Humor Chemistry",
    landingHeroSubtitle: "Who matches you best right now?",
    landingPreviewTitle: "Talk with these types",
    landingPreviewDesc: "Tap a card to choose your character",
    landingPreviewSeojunName: "Seojun",
    landingPreviewHaerinName: "Haerin",
    landingPreviewDoyunName: "Doyun",
    landingPreviewSeojunLine:
      "A relationship where we grow together sounds like it could go far.",
    landingPreviewHaerinLine:
      "What did you do today? Tell me everything, I'm seriously curious!",
    landingPreviewDoyunLine:
      "I'll show you through actions, not words. Want to make something together?",
    landingChatTitle: "This is how the chat flows",
    landingChatDesc: "A familiar Instagram DM-style screen",
    landingChatMsg1: "Hey! How are you feeling today? Tell me too.",
    landingChatMsg2: "Honestly... I've been feeling a little lonely lately.",
    landingChatMsg3: "I totally get that feeling. I'll stay by your side.",
    landingFeatureTitle: "Why MBTI Love Simulation?",
    landingFeature1Title: "MBTI-based conversation",
    landingFeature1Body:
      "Each of the 16 types has a different tone and reaction style, so it feels like talking to a real person.",
    landingFeature2Title: "Emotional reactions",
    landingFeature2Body:
      "From empathy to butterflies to tension, every message gets an emotional response from the character.",
    landingFeature3Title: "Love simulation",
    landingFeature3Body:
      "A low-pressure dating rehearsal through conversation, so you can gently unpack today's feelings.",
    landingEmotionalLine1: "That person you thought about alone at night,",
    landingEmotionalLine2: "you can meet them one more time here.",
    landingEmotionalSub: "No pressure, just focus on this conversation for now.",
  },
} as const;

export default TEXT;
